# Generated by Django 5.1.1 on 2024-10-02 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prouto',
            new_name='Produto',
        ),
    ]
